### ISSUE TITLE
Update RESOURCES.md with Elixir development resources

### ISSUE THREAD

**Issue by parkerl** [exercism/xelixir#103]
The information in here should not be about learning Elixir but rather links to documentation, community, etc.

- [x] Elixir documentation
- [x] hex.pm
- [x] irc
- [x] slack

**Comment by parkerl** [comment]
@nickpellant want to grab this one?

**Comment by nickpellant** [comment]
@parkerl Sure! I'm happy to take this one.

**Comment by Teapane** [comment]
Hey, what's the state on this? I have a bunch of `docs` I could put into the `README` but I don't want to submit a PR and step on toest if you've already started to work on it @nickpellant. :D

**Comment by nickpellant** [comment]
@Teapane Hi there! To be completely honest I've been swamped with other things, and haven't had chance to even get started with this. Feel free to jump in and add-add-add!

**Comment by Teapane** [comment]
@nickpellant Hey there! No worries, I know that feeling. :smile: Sounds good, I will get some stuff together and make a PR today. Thanks!
