### ISSUE TITLE
triangle: incorrect test in some tracks

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xelixir#106]
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

**Comment by bordeltabernacle** [comment]
There is this test:

```
  test "triangles violating triangle inequality are illegal 2" do
    assert Triangle.kind(2, 4, 2) == { :error, "side lengths violate triangle inequality" }
  end
```

**Comment by kytrinyx** [comment]
OK, cool. Let's wait until the discussion here settles: https://github.com/exercism/xerlang/issues/85 - then decide whether to remove it or change it.

**Comment by kytrinyx** [comment]
There was a bit of confusion with this issue. I've summarized my current understanding here: https://github.com/exercism/x-common/issues/202

I am closing this issue. If necessary I will open a new issue once we have come to an agreement about how to resolve the inconsistencies and what exact steps to take.
