### ISSUE TITLE
Upgrade code to Elixir 1.0

### ISSUE THREAD

**Issue by nhu313** [exercism/xelixir#12]
Placeholder to update the code to Elixir 1.0 once it is release.

**Comment by tjcelaya** [comment]
I started checking out the Elixir track today and noticed the examples hadn't been brought up to date with v1.0, could I help out with that? Would I just fork this repo and submit a pull request once I'm done?

**Comment by rubysolo** [comment]
Yes, that would be awesome.  Thanks!

**Comment by kytrinyx** [comment]
+1 That would be great! :heart:

**Comment by parkerl** [comment]
@kytrinyx @rubysolo close?
