### ISSUE TITLE
exercism fetch elixir hello-world not working

### ISSUE THREAD

**Issue by antonyr** [exercism/xelixir#137]
`exercism fetch elixir hello-world` command is not working. It returns 404 for me.
Please fix it.

**Comment by rubysolo** [comment]
Can you try just `exercism fetch elixir`?

**Comment by aamirtharaj-rpx** [comment]
I get following as the response

`
Usage: exercism fetch
   or: exercism fetch LANGUAGE EXERCISE`

**Comment by kytrinyx** [comment]
What does `exercism debug` output, please?

**Comment by aamirtharaj-rpx** [comment]
This is the output I got.
No help topic for 'debug'

**Comment by aamirtharaj-rpx** [comment]
I was able to get it working now. I had version 1.4.0 installed. After I upgraded to 2.2.4, things are breeze.

**Comment by antonyr** [comment]
Closing this issue based on @aamirtharaj-rpx comments

**Comment by kytrinyx** [comment]
Ah, OK, glad you got it sorted!

**Comment by aamirtharaj-rpx** [comment]
👍 Thank you.
On Mar 1 2016, at 11:43 pm, Katrina Owen <notifications@github.com> wrote:

Ah, OK, glad you got it sorted!
