### ISSUE TITLE
Fail the build on trailing whitespace?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xelixir#159]
There's one exercise (OCR numbers) where trailing whitespace is necessary for the test data, but (a) I don't know if that exercise is implemented, and (b) maybe we could put the actual test data in external files with a different file extension.

If we make sure not to screw up any exercises, though, we could fail the build if there's trailing whitespace by sticking this in the travis file.

```
- "! git grep ' $' -- \\*.exs"
```

**Comment by dalexj** [comment]
OCR is not on the elixir track right now

**Comment by kytrinyx** [comment]
Cool, so technically we could add this and then figure out how to deal with the whitespace issue in the OCR test data later (as my partner says: "This is a problem for future Katrina").

**Comment by parkerl** [comment]
@dalexj PR?
