### ISSUE TITLE
binary: improve tests for invalid numbers

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xelixir#164]
We should have separate tests for:

- alphabetic characters at the beginning of a valid binary number
- alphabetic characters at the end of a valid binary number
- alphabetic characters in the middle of an otherwise valid binary number
- invalid digits (e.g. 2)

If the test suite for binary has test cases that cover these edge cases, this issue can safely be closed.

See https://github.com/exercism/x-common/issues/95

**Comment by dalexj** [comment]
we currently have:

```elixir
  @tag :pending
  test "invalid binary is decimal 0" do
    assert Binary.to_decimal("carrot") == 0
  end

  @tag :pending
  test "invalid binary is decimal 0 II" do
    assert Binary.to_decimal("convert01") == 0
  end

  @tag :pending
  test "invalid binary is decimal 0 III" do
    assert Binary.to_decimal("10convert") == 0
  end

  @tag :pending
  test "22 is not a binary number" do
    assert Binary.to_decimal("22") == 0
  end
```

looks like this is all in place, unless `"carrot"` should be replaced by `"1carrot0"`

**Comment by kytrinyx** [comment]
I think `1carrot0` should come in addition to `carrot`.
