### ISSUE TITLE
[accumulate]: typespec vs. example implementation

### ISSUE THREAD

**Issue by NobbZ** [exercism/xelixir#175]
According to the typespec given in the exercise-stub, I'd expect `Accumulate.accumulate %{foo: :bar}, &(&1)` beeing a valid call of the function, but such is not caovered by the tests, as well as the example implementation does as well only handle lists.

So either the `@spec` is wrong and should be changed towards a more proper `@spec accumulate(list, (any -> any)) :: list` or the example is wrong and another clause should be added (`def accumulate(anything), fun) when not is_list(anything), do: anything |> Enum.into([]) |> accumulate(fun)`) as well as some tests that do test some other `Enumable.t`s that are not lists.

**Comment by bernardoamc** [comment]
I think you are right @NobbZ, `Enumerable.t` is too permissive in this case. Nice catch! 👍
