### ISSUE TITLE
typespecs and dialyzer

### ISSUE THREAD

**Issue by NobbZ** [exercism/xelixir#204]
I really like the typespecs which are provided with the module skeletons.

But sometimes they don't get updated in the example and/or the skelleton when tests are updated to expect new types, also I do often forget to update them when I catch for the newest version of the tests.

Is there an easy and hassle free way to actually do a check against the specs without wrapping everything into a mix-project?

And if so, could this be used in CI also?

Can we mention it in the README as a part of running the tests?

**Comment by kytrinyx** [comment]
Yes, we should definitely get this sort of check in place. I don't know what the hassle-free approach would be, though!

**Comment by lpil** [comment]
Would be interested to see how you do this. I've not found any examples of anyone running dialyzer on CI, probably due to the faff of generating and managing the PLT.

**Comment by devonestes** [comment]
So after some research there definitely isn't an "easy and hassle free" way of getting dialyzer set up without at least some more structure to the project (and by structure, I mean like Mix structure). Theoretically we could do something to make it work, but I question if the cost would be worth the benefit. I'm going to explore other ways that we can get the same benefit that wouldn't require such a gnarly change to the current codebase.

@lipil - yeah, the PLT takes forever and is a bummer, but luckily there's open source to the rescue! Check out this repo for pre-built PLTs for pretty much every combo of Erlang and Elixir versions that you can download (and info on how to make it all work): https://github.com/danielberkompas/travis_elixir_plts

**Comment by lpil** [comment]
This feels like yet another reason to adopt the standard Elixir project structure.

**Comment by devonestes** [comment]
@lpil - yeah, that definitely crossed my mind as I was working on this yesterday. I'm just not sure how we'll be able to do that within the structure that we need to keep to stay compliant with the x-exercises API. I'm going to do some research on what _exactly_ we need to implement to make sure the API works.

Part of me actually thinks we might be able to structure this as an umbrella app, but that's for further investigation. Of course, if you have any input, I'd be happy to hear it!

**Comment by lpil** [comment]
What is the part of the x-exercises API we would be unable to comply to?

**Comment by parkerl** [comment]
Closed by #258 and #237
