### ISSUE TITLE
Add test case for Prime Factors

### ISSUE THREAD

**Issue by sunboshan** [exercism/xelixir#206]
Consider add one more test case for [Prime Factors](https://github.com/exercism/xelixir/blob/master/exercises/prime-factors/prime_factors_test.exs)
```
test "10000000055" do
  assert PrimeFactors.factors_for(10000000055) == [5, 2000000011]
end
```

With my [first iteration](http://exercism.io/submissions/164bc866d4dd4ed989f2cf321b4658c0), it took 44189.1ms to pass this test. So need to tweak the solution to get this test pass in a decent time. I think it would serve a good test case to make your solution more optimized.

**Comment by kytrinyx** [comment]
I don't necessarily want to force people to consider optimization as a requirement, but thinking about trade-offs makes the exercise more interesting.

How about making it an optional test (as in "here's something to think about")? Do we have a mechanism for that @exercism/elixir?

**Comment by martinsvalin** [comment]
I think it'd be fine to simply say so in a code comment by the `@tag :pending`. Or you could be fancy and configure ExUnit to `exclude: [:pending, :extra_credit]`, and mark the test `@tag :extra_credit` instead of `:pending`.
