### ISSUE TITLE
Remove deprecated HashSet from `allergies` tests

### ISSUE THREAD

**Issue by devonestes** [exercism/xelixir#209]
I was just looking through the tests for another thing I'm doing, and I saw that we're still using `HashSet` in `allergies` here: https://github.com/exercism/xelixir/blob/master/exercises/allergies/allergies_test.exs#L75

That's now deprecated, so we'll have to update it to use MapSet. I'll probably take care of that today, but I wanted to write it down so I don't forget (or so someone else can take care of it).

**Comment by martinsvalin** [comment]
I had a quick look, as I didn't recall this exercise had anything to do with sets. It seems we're using sets to ignore order in the lists. Seems simpler to have the helper be something like

    def assert_same_elements(actual, expected) do
      assert Enum.sort(actual) == Enum.sort(expected),
             "Expected #{inspect actual} to have the same elements as #{inspect expected}"
    end
