### ISSUE TITLE
Accumulate's recursive function does not actually test recursive mapping

### ISSUE THREAD

**Issue by mgwidmann** [exercism/xelixir#216]
The test here:
https://github.com/exercism/xelixir/blob/master/exercises/accumulate/accumulate_test.exs#L35

Looks like its attempting to check that the `accumulate/2` function will continue mapping if it encounters a list as one of the items in the list. This however is not true since the 2nd level of lists is just created in the anonymous function.

The test IMO should be more like:

```elixir
chars = ~w(a b c)
nums  = ~w(1 2 3)
list = for c <- chars, num <- nums, do: c <> num
expected = [["A1", "A2", "A3"], ["B1", "B2", "B3"], ["C1", "C2", "C3"]]
assert Accumulate.accumulate(chars, &String.upcase/1) == expected
```

@jeg2 I belive you submitted this exercism

**Comment by JEG2** [comment]
Uh, I don't remember ever submitting an exercism.  😄

**Comment by mgwidmann** [comment]
Is that not you at the bottom of the readme?? http://exercism.io/exercises/elixir/accumulate/readme

**Comment by JEG2** [comment]
That's me.  Wild.  I wonder what I said???

**Comment by dalexj** [comment]
I believe you misread the actual code from the test. each char is being mapped with the function given, which returns a list with the char and `[1,2,3]` as strings. the accumulate function does nothing special if the list passed in has a list as an element

I do agree that this test is confusingly named though

**Comment by mgwidmann** [comment]
So I understood the test name to mean that the map function is applied recursively if a list element is encountered while iterating.

Thats why I put a recursive call in my implementation:
http://exercism.io/submissions/b907c6a12d6e4b0fae4bb664b3b8adbf#L22

Which I found out that the test suite passes without that line since the passed in anonymous function performs the second level "map".

I'm not sure what its trying to test if it doesn't require recursive mapping.

**Comment by dalexj** [comment]
so yes, I think the test name is confusing and should be changed here

**Comment by parkerl** [comment]
Yes, this looks confusing. Would someone mind submitting a PR with a better test description?

**Comment by martinsvalin** [comment]
Is there a way you can reach this last test and have it fail? I don't see what it drives out, and the test itself is adding non-essential complexity (passing in a function that closes over a list), that has nothing to do with the function tested.

In a code base of my own, I'd remove it. If we change the name, I'd suggest `"accumulate lists"`. Still pretty ambiguous, but perhaps less likely to lead someone to implement a deep map.

**Comment by mgwidmann** [comment]
@martinsvalin I was suggesting, as you are, that we change the test (leaving the name) to have the user implement a deeply recursive map function. However useless it might be in real life, the exercise would be a good addition.

**Comment by kytrinyx** [comment]
> That's me. Wild. I wonder what I said???

@JEG2 I think this was during the Rogues retreat, and we were casually chatting about mentoring people, and you mentioned that you had gotten some of your mentees to reimplement enumerable methods.

**Comment by JEG2** [comment]
Ah, could be!

**Comment by tejasbubane** [comment]
I would suggest using `accumulate` itself instead of `for` and call it `"nested accumulate"`:

```elixir
  test "nested accumulate" do
    chars = ~w(a b c)
    nums  = ~w(1 2 3)
    fun = fn(c) -> Accumulate.accumulate(nums, &(c <> &1)) end
    expected = [["a1", "a2", "a3"], ["b1", "b2", "b3"], ["c1", "c2", "c3"]]
    assert Accumulate.accumulate(chars, fun) == expected
  end
```

**Comment by parkerl** [comment]
I'm scratching my head on this. It looks to me like the original thought was to drive out deep mapping with something like:


```  
test "accumulate recursively" do
    values = [[1,2,3], [4, 5, 6]]
    fun = fn(num) -> num * 2 end
    expected = [[2, 4, 6], [8, 10, 12]]
    assert Accumulate.accumulate(values, fun) == expected
  end
```

@tejasbubane the change in your PR illustrates that `Accumulate.accumulate/2` can take a function that allows it to compute the permutations of two lists. However, I don't see it driving out any additional behavior. This test, as @martinsvalin points out, has the non-essential complexity of closing over `num` in the passed function.

My recommendation is that we either take this test out or make it drive out additional behavior.

**Comment by tejasbubane** [comment]
@parkerl Agreed. It does not drive any additional behaviour. My idea was to give a better description to the test (`nested` instead of `recursive`) and since we already have `accumulate` use that itself instead of `for`. I am perfectly fine with removing the test entirely since it does not test anything new which the rest of the tests don't.
