### ISSUE TITLE
The custom-set exercism is based around the deprecated Set module and removed Set behaviour 

### ISSUE THREAD

**Issue by lpil** [exercism/xelixir#217]
Hello!

The `Set` module was deprecated in 1.2, and the behaviour has since been removed. It's not possible to directly port the changes to the `MapSet` replacement as it's a single data structure implementation rather than a behaviour with a default implementation.

This exercise needs to be removed, or entirely re-written. :(

I notice there are other open issues for this exercise. #198 #180 #121

**Comment by devonestes** [comment]
Yeah, at this point we just need to totally re-write the test suite for that exercise, so that's going to happen eventually. I'm confident that we can keep the exercise as it is, though, and just replace the test suite.

**Comment by lpil** [comment]
When we do so it would be good to add a note saying that in the real world we should use `MapSet` instead of inventing our own map :)
