### ISSUE TITLE
elixir nucleotide_count: map ordering issue

### ISSUE THREAD

**Issue by mcpherson** [exercism/xelixir#233]
I looked around and haven't seen this raised anywhere else, so here goes.

`@nucleotides` is arranged in alphabetical order (`[?A, ?C, ?G, ?T]`) but test results for `histogram` expect a map with a different ordering:

```elixir
iex> DNA.histogram('AATAA')
%{?A => 4, ?T => 1, ?C => 0, ?G => 0}
```

Note `T` in second position.

In my own solution I just reordered `@nucleotides` to `[?A, ?T, ?C, ?G]` but this is likely cheating. The correct solutions that I've seen get the proper ordering manually (not using `@nucleotides`). This also seems like a hack. Maybe I'm missing an obvious solution, but perhaps the best thing to do is to change `@nucleotides` ordering in the source to `nucleotide_text.exs`?

**Comment by NobbZ** [comment]
In a map order should not matter since it is compared by keys.

**Comment by mcpherson** [comment]
OK, I guess I need to think about that and understand what happens here (in a test):

```elixir
expected = %{?A => 20, ?T => 21, ?C => 12, ?G => 17}
assert DNA.histogram(s) == expected
```

I will explore in Iex and close this if it turns out I misunderstood this.

**Comment by mcpherson** [comment]
Indeed, my bad. Learned (here) that maps are compared by key. Closing.
