### ISSUE TITLE
Adopt Mix

### ISSUE THREAD

**Issue by Trevoke** [exercism/xelixir#245]
I'm going through scala and they chose sbt as a project management structure to run the tests.

Since we're ALWAYS gonna have a Mix project when working with Elixir, unless we're working on one-offs, why not just have Mix in there? One benefit is that we could write tasks in there for:

1. Running the tests
2. Checking with Dialyxir 
3. Submitting to exercism

**Comment by parkerl** [comment]
Thanks for asking. In the interest of keeping things simple we are going to continue with our current setup.  Thanks

**Comment by Trevoke** [comment]
In the interest of keeping things simple, why is dialyxir in there at all?
