### ISSUE TITLE
No information anywhere on the meaning of the type annotations

### ISSUE THREAD

**Issue by Trevoke** [exercism/xelixir#246]
I expected to find information on this somewhere around http://exercism.io/languages/elixir/tests but nope, nada.

As it stands, it's completely useless for people who are new to the language, or worse, it might actually get in the way of what exercism is trying to accomplish.

**Comment by parkerl** [comment]
@Trevoke sorry for your frustration. Adding type annotations is an Elixir best practice. There meaning can be found in the Elixir "Getting Started" guides. Perhaps we could point that out more directly. We don't currently encourage that the types be checked by the end user. I'm hoping that at some point we can offer some guidance as to how advanced users might be able to use them.

Thanks,

**Comment by Trevoke** [comment]
This is the second time a conversation I start is summarily closed. Should I open a new one to bring up a new argument?
