### ISSUE TITLE
`markdown` should be a refactoring exercise

### ISSUE THREAD

**Issue by devonestes** [exercism/xelixir#252]
The current implementation of the `markdown` exercise isn't exactly what is intended in the README, and I worry that folks will be confused. If you take a look at the README, it makes it clear that the user is given a very poorly factored version of the exercise and their job is to refactor it, but that's not really we have here.

For some background, here's the original issue that was raised about adding more refactoring exercises: https://github.com/exercism/discussions/issues/24

And here's the link to the README and such in the `x-common` repo: https://github.com/exercism/x-common/pull/262/files

@yeongsheng-tan, do you want to take a crack at this since you did the initial implementation? There isn't a whole lot more that you'd need to do - just take your existing `example.exs` and make it way worse, then put that in the `markdown.exs` file so that's what's served to users.

If you have any questions, let me know! I'd be happy to help whoever wants to take this on.

**Comment by parkerl** [comment]
@devonestes nice catch. I completely missed that. My bad. @yeongsheng-tan are you up for un-factoring that exercise?
