### ISSUE TITLE
Abbreviate test/README doesn't explain expected behavior of consecutive capital letters

### ISSUE THREAD

**Issue by bbugh** [exercism/xelixir#253]
What acronym should the word "POtatO" result in? 

This isn't in the README, and the tests don't test for it, but it is an unchecked edge case that would be good to know.

Looks like this was written by @monkbroc

**Comment by devonestes** [comment]
@bbugh Thanks for the issue! I think this is something that should be raised in the [x-common](https://github.com/exercism/x-common) repo where the exercises are defined for all languages - that's where the READMEs and the test data are defined. Feel free to raise this issue there!
