### ISSUE TITLE
Implement `grep` exercise

### ISSUE THREAD

**Issue by devonestes** [exercism/xelixir#263]
We currently do not have the `grep` exercise implemented in xElixir, and it would be good to add.

Find more information on how to add a new exercise here: https://www.sitepoint.com/exorcise-your-newbie-demons-by-contributing-to-exercism/

Here is the link to the README for this exercise: https://github.com/exercism/x-common/blob/master/exercises/grep/description.md

And here is the link to the test data for this exercise: https://github.com/exercism/x-common/blob/master/exercises/grep/canonical-data.json

If there are any other questions on how to implement this exercise then don't hesitate to reach out to a maintainer!

**Comment by lpil** [comment]
I'll take this one. :)

**Comment by parkerl** [comment]
Closed by #265
