### ISSUE TITLE
Move from `:pending` to `:skip`

### ISSUE THREAD

**Issue by parkerl** [exercism/xelixir#266]
I put in a PR to fix the issues we had with `:skip`. Once it is released we can make the switch.

https://github.com/elixir-lang/elixir/pull/5305

**Comment by NobbZ** [comment]
As I do understand the semantics of skip and pending then I'd prefer pending over skip. 

When I see skip I do read it only as to not run the tagged test for whatever reason, while pending has some kind of do not run now, it's not implemented but on my to-do list. 

So using tags semantic ally there could even be some new ones which are used to exclude bonus tests which do increase the difficulty of the exercise.

**Comment by devonestes** [comment]
Just saw that your PR has been merged (great patch!) and this is now working, which should unblock us on this, right?

@NobbZ I kind of agree with you - `:skip` is rather unfortunately named. But given that, I think it's still important to use the convention that's been decided on even if it's slightly less than perfect.

**Comment by parkerl** [comment]
@devonestes yeah we just need to wait for it to be released now.

**Comment by devonestes** [comment]
![D'oh](https://media.tenor.co/images/d44ea8bbc007e5074d987278092f62c5/raw)

Oh yeah, we aren't building off master. Well, hopefully it'll be released soon!

**Comment by devonestes** [comment]
@parkerl I think this is out in 1.4 now, right?

**Comment by parkerl** [comment]
@devonestes sorry I have been AWOL. Yes I think we need to move to 1.4 and unblock this issue.

**Comment by devonestes** [comment]
No need to be sorry! That's why the rest of us are here to help. I'll probably be rather absent for a month or two this summer, too 👶

**Comment by parkerl** [comment]
Let's do this.

**Comment by parkerl** [comment]
@devonestes I'm on the fence about this after further thought. This change will effect users and require them to be on version `1.4` in order for the exercises to work correctly. I'm not sure it is fair for us to require them to be that up-to-date. What do you think? Maybe we after 1.4 has been out for a bit longer?

**Comment by devonestes** [comment]
I was thinking about that, too. In general, I'm all for things that push people to upgrade to the newer and better things. However, that's dependent on there being a good way to tell folks that they need to upgrade, and I'm not 100% sure that we have that at the moment. It wouldn't be too hard to add, though.

I guess it's a bigger question that we should decide now that it's becoming a thing - which versions of Elixir do we support? Only the most recent version? Any version that's still getting security updates?
