### ISSUE TITLE
run-length-encoding tests conflict with description of exercise in README

### ISSUE THREAD

**Issue by daveyarwood** [exercism/xelixir#292]
I noticed that the expected results in the run-length-encoding tests suggest that the solution [should translate a single letter like `H` as `1H`](https://github.com/exercism/xelixir/blob/master/exercises/run-length-encoding/rle_test.exs#L20-L28).

However, the [README description](https://github.com/exercism/x-common/blob/master/exercises/run-length-encoding/description.md) suggests that the solution should leave single letters alone, i.e. `H` remains `H`.

I'd be happy to make a PR to fix this in the test cases and example solution -- just wanted to check first to make sure that's how we want to resolve this.

**Comment by devonestes** [comment]
@daveyarwood Good catch - the README does seem to indicate that our implementation is incorrect! A PR would be very welcome if you wanted to tackle that 👍
