### ISSUE TITLE
adding `mix` to the mix

### ISSUE THREAD

**Issue by bunnymatic** [exercism/xelixir#295]
Have you ever considered setting up exercises with `mix` in the mix?

As a new elixir user, I was interested in adding `credo` to my project to see how stylee my code was but it says "add to your `mix.exs`" and it made me wonder how `mix` works into an elixir project?

I know other languages have a different directory structure (e.g. `java`).  Setting up the initial directory structure for exercises that would support `mix` or even with a default `mix.exs` file might  be nice.

Thoughts?

**Comment by rubysolo** [comment]
There has been some discussion around this.  (See Issue #218 and Issue #245 for examples).

I am personally neutral -- I think it's nice for beginners to focus on just the language instead of having to learn the ecosystem, but I understand that it's probably more idiomatic to use mix than not.

**Comment by bunnymatic** [comment]
Yeah - i see how the system is nice and simple - not mixing in any build tools.

I know the Java track uses `gradle` but other tracks i've run (ruby, clojure, javascript) don't have anything of note.  

just thought i'd ask.

thanks for the response
