### ISSUE TITLE
Clarification of README in sublist problem

### ISSUE THREAD

**Issue by redvers** [exercism/xelixir#30]
Given that there is a set progression of exercises there is some tendency in the users to almost "inherit" guidance from previous exercises if the current exercise appears to be an expansion of the previous.

For example, the previous exercise "list-ops" had the explicit instruction:
"Implement a series of basic list operations, without using existing functions."

When the next exercise is another list operations (specifically, sublist) there is some confusion as to whether there is an expectation for the users to write all methods from first principles or use the built-in list operators.

**Comment by parkerl** [comment]
This seems stale. Closing.
