### ISSUE TITLE
Add BEAM Gitter channel to docs

### ISSUE THREAD

**Issue by parkerl** [exercism/xelixir#302]
Add the gitter channel https://gitter.im/exercism/xerlang (from #296) to:

https://github.com/exercism/xelixir/blob/master/docs/INSTALLATION.md
https://github.com/exercism/xelixir/blob/master/docs/RESOURCES.md
https://github.com/exercism/xelixir/blob/master/docs/LEARNING.md

**Comment by ckhrysze** [comment]
Any reason to not also add https://elixirforum.com/ to at least resources and learning?

**Comment by devonestes** [comment]
Resolved with #311
