### ISSUE TITLE
Changes to Bowling doc or test

### ISSUE THREAD

**Issue by NickNeck** [exercism/xelixir#306]
In the [documentation](https://github.com/exercism/xelixir/blob/master/exercises/bowling/bowling.exs#L13) an atom ```: ok``` is required as a return value for ```roll```. But this will break the test at [line 12](https://github.com/exercism/xelixir/blob/master/exercises/bowling/bowling_test.exs#L12).

**Comment by devonestes** [comment]
Good catch! I think it would be preferable to remove that line from the function documentation rather than break the test. Do you want to update it? If not then I'll take care of it.
