### ISSUE TITLE
Exercise bank-account doesn't require a `close_bank` implementation.

### ISSUE THREAD

**Issue by awochna** [exercism/xelixir#319]
All tests pass without ever having it implement a `close_bank/1` function. We should probably just add a test for it.

However, I haven't been able to gather from the instructions what the response is supposed to be when trying to query the balance or update a closed account, just that "operations against a closed account must fail."

**Comment by devonestes** [comment]
@awochna Good catch! If you're up for it, I'd be happy to review a PR and offer any help I can. If you don't want to tackle this yourself, though, just let me know and either I or someone else will get to adding those tests.

Thanks again for the contribution!
