### ISSUE TITLE
Meetup - 5th Monday

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xelixir#38]
There is an interesting edge case in the meetup problem:
some months have five Mondays.

March of 2015 has five Mondays (the fifth being March 30th), whereas
February of 2015 does not, and so should produce an error.

------

Thanks, @JKesMc9tqIQe9M for pointing out the edge case.
See [exercism.io#2142](https://github.com/exercism/exercism.io/issues/2142).

**Comment by pminten** [comment]
That's not a problem here, the exercise doesn't allow for passing the fourth week. :stuck_out_tongue:

I'll go and fix it.

**Comment by kytrinyx** [comment]
Hah, that certainly solves that problem :)

**Comment by kytrinyx** [comment]
As someone mentioned in the original issue:

> You can't regularly schedule a meetup on the fifth week of every month because February usually doesn't have a fifth week at all (and no month ever has a full fifth week). It's nonsense to even support "fifth" as an input in the first place. I think that first-fourth, last, teenth are the only scheduling inputs that should be supported.

What do you think, should we just bail on the fifth week idea?

**Comment by pminten** [comment]
All things considered I think that's best, yes. The consequence of including it would be to introduce much extra complexity.

Katrina Owen <notifications@github.com> schreef op 22 maart 2015 21:37:08 CET:
>As someone mentioned in the original issue:
>
>> You can't regularly schedule a meetup on the fifth week of every
>month because February usually doesn't have a fifth week at all (and no
>month ever has a full fifth week). It's nonsense to even support
>"fifth" as an input in the first place. I think that first-fourth,
>last, teenth are the only scheduling inputs that should be supported.
>
>What do you think, should we just bail on the fifth week idea?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/xelixir/issues/38#issuecomment-84697072

-- 
Verzonden van mijn Android telefoon met K-9 Mail.

**Comment by kytrinyx** [comment]
Cool, I'll close the issue and the PR. Thanks!
