### ISSUE TITLE
Update the Elixir track to target version 1.2

### ISSUE THREAD

**Issue by parkerl** [exercism/xelixir#87]
We should update our target version to Elixir 1.2. 
 - [x] Update CI
 - [x] Fix test failures
 - [x] Update documentation
 - [x] Clean up pipe warnings
```
#We are getting quite a few of these in the examples after the 1.2 upgrade

warning: you are piping into a function call without parentheses, which may be ambiguous. Please wrap the function you are piping into in parentheses. For example:

    foo 1 |> bar 2 |> baz 3

Should be written as:

    foo(1) |> bar(2) |> baz(3)
```

**Comment by bordeltabernacle** [comment]
Sorry for the extra commits, shoulda squashed them! https://github.com/exercism/xelixir/pull/111

**Comment by bordeltabernacle** [comment]
Sorry about all the extra commits, shoulda squashed! https://github.com/exercism/xelixir/pull/112
