### ISSUE TITLE
Running doctest's

### ISSUE THREAD

**Issue by elvanja** [exercism/xelixir#97]
Would it be possible to run doctest's along the regular ones, but when exercises are pulled from exercism.io? (as opposed to working with mix within this project)

Currently, the mix setup from the root of this project isn't added to exercism's elixir folder, and executing e.g. `elixir phone_number_test.exs` executes only the ones in the test file.

The only workaround I have for now is:
* compile the main module, e.g. `elixirc phone_number.exs`
* add `doctest Phone` beneath `use ExUnit.Case, async: true` in test file
Then, running `elixir phone_number_test.exs` runs the doctest as well.

The only problem with this is that one needs to execute the compile step for every change to the main module. I guess this could be made into a small script, e.g `run_tests.sh`.
```bash
elixirc main_module.exs && elixir test_module.exs
```

Since I'm new to Elixir, I don't know if this would work in all cases (Windows, ...?). What do you think? P.S. I'd be glad to PR this if above suggestion is on the right track.

Related issues: https://github.com/exercism/xelixir/issues/23
Less, but still related issues: https://github.com/exercism/xelixir/issues/96, https://github.com/exercism/xelixir/issues/47

**Comment by dalexj** [comment]
commenting on an old issue, but it seems very few of the exercises have doctests (quick search says maybe 12/45).

also the tests should cover all the functionality each exercise is supposed to implement, so I don't see anything gained from running doctest as well.

**Comment by parkerl** [comment]
@dalexj the only benefit would be to make sure the code dose not move away for the docs. But if that happens, we reviewers have fallen down on the job. Closing. Thanks.
